Read binaries as bytes instead of string
tobischo/gokeepasslib pull request #71
Opened 2021-09-24 19:55 UTC by Footmau

I suggest to replace string return parameter of GetContent() with bytes array because it is much more common case since most of users store some binary files here.

2021-09-25 18:21 UTC, tobischo commented
While I understand the idea behind it, I am not sure I want to introduce this breaking change.

We can introduce a `GetByteContent()` func and a `GetStringContent()` (or `GetContentAsBytes()`, `GetContentAsString()`) and label `GetContent()` as deprecated

2021-09-25 18:30 UTC, Footmau commented
Sounds good, I'll update the changes.

2021-09-26 07:56 UTC, tobischo requested changes
Looks good. It would be nice if we could have godoc comments with the matching func names

2021-09-26 07:56 UTC, tobischo commented on binary.go
> +// GetContent returns a bytes array which is the content of a binary
Needs adaption for matching godoc standards

2021-09-26 07:56 UTC, tobischo commented on binary.go
> +// GetContent returns a string which is the plaintext content of a binary
`GetContentString returns...`

2021-09-26 15:26 UTC, Footmau commented on binary.go
> +// GetContent returns a string which is the plaintext content of a binary
Thanks, done.

2021-09-26 18:42 UTC, tobischo approved these changes

2021-09-26 18:43 UTC, merged